# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# References:
# 1. https://github.com/marketplace/actions/deploy-to-github-pages

name: Default

on:
  push:
    paths-ignore:
      - readme.md
      - docs/
    branches: [main]

jobs:
  build-and-deploy:
    name: Builds a project and deploys to production
    if: ${{ !contains(github.event.head_commit.message, '[skip') || !contains(github.event.head_commit.message, 'ci]') }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: 🛎️ Checkout
         # If you're using actions/checkout@v2 you must set persist-credentials
         # to false in most cases for the deployment to work correctly
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > .npmrc

      - name: 🔧 Install and build
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /bth-portfolio_gh-pages
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}

      - name: Export the app to static HTML
        run: |
          npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /bth-portfolio_gh-pages
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}

      - name: Don't run the published files through Jekyll
        run: |
          touch ./out/.nojekyll

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set a branch in which the action will deploy production-ready files
          BRANCH: gh-pages
          # Set a folder that will be used by the action for further deployment
          # process
          FOLDER: out
          # Automatically remove deleted files from the deployment branch
          CLEAN: true
